version = 1

[[analyzers]]
name = "dart-analyze"
type = "community"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "18"
  language_version = "1.9"

[[analyzers]]
name = "dart-analyze"
type = "community"

[[transformers]]
name = "ktlint"