version = 1

test_patterns = ["test/", "tests/"]

[[analyzers]]
name = "dart-analyze"
type = "community"
enabled = true
path = "./lib"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "18"
  language_version = "1.9"

[[transformers]]
name = "ktlint"