// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqfnwRsAVTeXF1TmjdpFjw_jHJ6z06ZX4',
    appId: '1:581946205691:web:f1f35ea1ba6acf52aed75e',
    messagingSenderId: '581946205691',
    projectId: 'flutter-firebase-feature-flags',
    authDomain: 'flutter-firebase-feature-flags.firebaseapp.com',
    storageBucket: 'flutter-firebase-feature-flags.appspot.com',
    measurementId: 'G-JTMYTD0JJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnrgW0YcnBAThUudVYNx7qMUNtNrdB1Dw',
    appId: '1:581946205691:android:7f5c6b4cc3b0713eaed75e',
    messagingSenderId: '581946205691',
    projectId: 'flutter-firebase-feature-flags',
    storageBucket: 'flutter-firebase-feature-flags.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABjT0rI-pweXEh_XA6cPT1tb-7f8xJNOs',
    appId: '1:581946205691:ios:2513137fdd0cecf2aed75e',
    messagingSenderId: '581946205691',
    projectId: 'flutter-firebase-feature-flags',
    storageBucket: 'flutter-firebase-feature-flags.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseFeatureFlags',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABjT0rI-pweXEh_XA6cPT1tb-7f8xJNOs',
    appId: '1:581946205691:ios:2513137fdd0cecf2aed75e',
    messagingSenderId: '581946205691',
    projectId: 'flutter-firebase-feature-flags',
    storageBucket: 'flutter-firebase-feature-flags.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseFeatureFlags',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqfnwRsAVTeXF1TmjdpFjw_jHJ6z06ZX4',
    appId: '1:581946205691:web:48615574376d0393aed75e',
    messagingSenderId: '581946205691',
    projectId: 'flutter-firebase-feature-flags',
    authDomain: 'flutter-firebase-feature-flags.firebaseapp.com',
    storageBucket: 'flutter-firebase-feature-flags.appspot.com',
    measurementId: 'G-6299CJNSZD',
  );
}
