name: DeepSource Analyze

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Run DeepSource analysis
        run: |
          # Install DeepSource CLI
          curl https://deepsource.io/cli | sh
          
          # Run the DeepSource analysis
          ./bin/deepsource report --analyzer dart --analyzer-type community
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}